/// Central repository for all Medical, Legal, and Breeding Disclaimers used throughout Animal Birthday Predictor.
/// The client can easily provide/update the exact wording directly in this file.
class AppDisclaimerContent {
  static const String title = 'Medical, Breeding & Legal Disclaimer';
  static const String version = '1.0';
  static const String lastUpdated = 'August 2026';

  static const String shortSummary =
      'Animal Birthday Predictor (ABP) provides mathematical estimations and record-keeping tools for breeding management. Calculations are based on standard veterinary biological models and are NOT a substitute for professional veterinary diagnosis, ultrasound examination, or clinical care.';

  static const List<({String title, String content, String icon})> sections = [
    (
      title: '1. Informational & Decision-Support Purpose',
      content:
          'All algorithms, gestation timelines, foaling/whelping due dates, and milestone charts provided by this application are designed strictly for logistical planning and informational decision support. They do not constitute guaranteed biological outcomes or contractual delivery dates.',
      icon: 'info',
    ),
    (
      title: '2. Licensed Veterinary Consultation Required',
      content:
          'This software is not a veterinary medical device and does not provide veterinary medical advice, diagnosis, or treatment plans. You must always consult a qualified, licensed veterinarian for reproductive management, ultrasound scanning, pregnancy confirmation, twin reduction, medication administration, and dystocia emergencies.',
      icon: 'medical',
    ),
    (
      title: '3. Biological Gestation Variability',
      content:
          'Normal gestation length varies naturally based on species, breed, maternal age, litter size, photoperiod, and seasonal factors:\n'
          '• Equine Gestation: Standard is 340 days, but normal viable foaling ranges from 320 to 365+ days.\n'
          '• Canine Gestation: Standard is 63 days, with normal whelping ranging from 58 to 68 days.\n'
          'Users are advised to monitor physical signs (e.g. udder enlargement, wax appearance, milk calcium levels, temperature drops) in addition to calculated dates.',
      icon: 'clock',
    ),
    (
      title: '4. Ultrasound Scans & Twin Warning Notice',
      content:
          'Ultrasound scan milestones (such as Day 14–16, Day 28–30, and Day 45 scans) must be performed and interpreted by a certified equine/canine reproduction veterinarian. In the event of suspected equine twin vesicles, immediate veterinary action is necessary to prevent spontaneous abortion or complications.',
      icon: 'scan',
    ),
    (
      title: '5. Limitation of Liability',
      content:
          'To the fullest extent permitted by law, Animal Birthday Predictor (ABP), its creators, developers, and affiliated entities disclaim all liability for any direct, indirect, incidental, or consequential losses, damages, or complications arising from the use of or reliance upon calculations, certificates, preventative care reminders, or data generated by this application.',
      icon: 'gavel',
    ),
    (
      title: '6. Breeder Responsibility & Due Diligence',
      content:
          'The animal owner, stud manager, or breeder assumes sole responsibility for ensuring accurate service date entries, verifying animal microchip IDs, maintaining clean foaling environments, and arranging timely veterinary attendance.',
      icon: 'shield',
    ),
  ];

  static const String certificateDisclaimer =
      'DISCLAIMER: This certificate is generated based on breeder-entered data and standardized gestational models for record-keeping purposes. It does not replace a physical veterinary certificate of soundness or guarantee biological outcomes.';
}
